
version: 0.2

phases:
  install:
    commands:
      - echo "No installation necessary"
  pre_build:
    commands:
      - echo "Pre-build steps not required"
  build:
    commands:
      - echo "Copying files from source to destination"
      - rm -rf ./dist/*
      - cp -R ./src/* ./dist/
  post_build:
    commands:
      - echo "Build process completed"
      - echo "Delete all files from the root of the S3 bucket"
      - aws s3 rm s3://chrisjiang.net/ --recursive
      - echo "Copy new files to S3 bucket"
      - aws s3 cp ./dist/ s3://chrisjiang.net/ --recursive
      - echo "Build and deploy completed successfully"

artifacts:
  files:
    - '**/*'
  base-directory: 'dist' # Ensure this matches where your output files are stored

cache:
  paths:
    - 'None' # No caching needed if no dependencies are installed